apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o DRASTIC -f docker-stack-dev.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafdrop
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o DRASTIC -f docker-stack-dev.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/drastic: "true"
        io.kompose.service: kafdrop
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERCONNECT
              value: kafka:9092
          image: obsidiandynamics/kafdrop
          name: kafdrop
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
