version: "3.2"
services:
#   trellis:
#       - 80:8080

  cassandra-1:
    image: cassandra:3.11.11
    environment:
      CASSANDRA_BROADCAST_ADDRESS: localhost
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-1
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
      - target: 7000
        published: 7000
        protocol: tcp
        mode: host
    volumes:
      - ./cassandra-data:/var/lib/cassandra
    networks:
      drastic:

  cassandra-init:
    image: cassandra
    depends_on:
      - cassandra-1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    volumes:
      - ./trellis.cql:/trellis.cql
    command: cqlsh cassandra-1 -f /trellis.cql
    networks:
      - drastic

  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - 2181:2181
    networks:
      drastic:

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    networks:
      drastic:
    environment:
      KAFKA_LISTENERS: INT://kafka:9092,EXT://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_ADVERTISED_LISTENERS: INT://kafka:9092,EXT://pop-os:9094
      #KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092
      #KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      #KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      #KAFKA_ADVERTISED_PORT: 9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafkacat:
    image: confluentinc/cp-kafkacat
    command: sleep infinity
    networks:
      drastic:

  fuseki:
    image: gregjan/fuseki:latest
    command: [ "--tdb2", "--update", "--loc", "databases/DB2", "/ds" ]
    ports:
      - target: 3030
        published: 3030
        protocol: tcp
        mode: host
    volumes:
      - ./fuseki-data:/fuseki/databases
    networks:
      drastic:

networks:
  drastic:
    driver: overlay
