apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-fuseki-service
  name: fuseki
spec:
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3030
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-fuseki-deployment
status:
  loadBalancer: {}
